package com.setur.contact.enums;

public enum ErrorCode {

    CONTACT_NOT_FOUND_EXCEPTION,
    COMMUNICATION_NOT_FOUND_EXCEPTION,
    REPORT_NOT_FOUND_EXCEPTION,
    REPORT_DETAIL_NOT_FOUND_EXCEPTION
}
